//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Savory.AutoURLValidateService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="openf2Soap", Namespace="http://tempuri.org/")]
    public partial class openf2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback VCM_AutoURL_Validate_User_InfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUtcSqlServerDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckUserStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserLoginActivatationFLagOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserPasswordFlagOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmailIDFromUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserCustomerDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserSecurityQuestion_And_AnswerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCMEUserIdFromGuidOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCMEUserGuidOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserstateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAutoURLGeoIPInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeastApps_SharedAutoURL_ValidateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeastApps_SharedAutoURL_UpdateClickCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeastApps_SharedAutoURL_StoppedByInitiatorOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUserLoginMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetUserPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public openf2() {
            this.Url = global::Savory.Properties.Settings.Default.Savory_AutoURLValidateService_openf2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event VCM_AutoURL_Validate_User_InfoCompletedEventHandler VCM_AutoURL_Validate_User_InfoCompleted;
        
        /// <remarks/>
        public event GetUtcSqlServerDateCompletedEventHandler GetUtcSqlServerDateCompleted;
        
        /// <remarks/>
        public event CheckUserStatusCompletedEventHandler CheckUserStatusCompleted;
        
        /// <remarks/>
        public event SetUserLoginActivatationFLagCompletedEventHandler SetUserLoginActivatationFLagCompleted;
        
        /// <remarks/>
        public event SetUserPasswordFlagCompletedEventHandler SetUserPasswordFlagCompleted;
        
        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
        
        /// <remarks/>
        public event GetEmailIDFromUserIDCompletedEventHandler GetEmailIDFromUserIDCompleted;
        
        /// <remarks/>
        public event GetUserCustomerDetailsCompletedEventHandler GetUserCustomerDetailsCompleted;
        
        /// <remarks/>
        public event GetUserSecurityQuestion_And_AnswerCompletedEventHandler GetUserSecurityQuestion_And_AnswerCompleted;
        
        /// <remarks/>
        public event GetUserIDCompletedEventHandler GetUserIDCompleted;
        
        /// <remarks/>
        public event GetCMEUserIdFromGuidCompletedEventHandler GetCMEUserIdFromGuidCompleted;
        
        /// <remarks/>
        public event SaveCMEUserGuidCompletedEventHandler SaveCMEUserGuidCompleted;
        
        /// <remarks/>
        public event ValidateUserCompletedEventHandler ValidateUserCompleted;
        
        /// <remarks/>
        public event GetUserstateCompletedEventHandler GetUserstateCompleted;
        
        /// <remarks/>
        public event GetAutoURLGeoIPInfoCompletedEventHandler GetAutoURLGeoIPInfoCompleted;
        
        /// <remarks/>
        public event BeastApps_SharedAutoURL_ValidateCompletedEventHandler BeastApps_SharedAutoURL_ValidateCompleted;
        
        /// <remarks/>
        public event GetUserNameCompletedEventHandler GetUserNameCompleted;
        
        /// <remarks/>
        public event AuthenticateUserCompletedEventHandler AuthenticateUserCompleted;
        
        /// <remarks/>
        public event BeastApps_SharedAutoURL_UpdateClickCountCompletedEventHandler BeastApps_SharedAutoURL_UpdateClickCountCompleted;
        
        /// <remarks/>
        public event BeastApps_SharedAutoURL_StoppedByInitiatorCompletedEventHandler BeastApps_SharedAutoURL_StoppedByInitiatorCompleted;
        
        /// <remarks/>
        public event SendUserLoginMailCompletedEventHandler SendUserLoginMailCompleted;
        
        /// <remarks/>
        public event ResetUserPasswordCompletedEventHandler ResetUserPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VCM_AutoURL_Validate_User_Info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet VCM_AutoURL_Validate_User_Info(string URLEncrypted, string IPAddress, int ApplicationCode) {
            object[] results = this.Invoke("VCM_AutoURL_Validate_User_Info", new object[] {
                        URLEncrypted,
                        IPAddress,
                        ApplicationCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void VCM_AutoURL_Validate_User_InfoAsync(string URLEncrypted, string IPAddress, int ApplicationCode) {
            this.VCM_AutoURL_Validate_User_InfoAsync(URLEncrypted, IPAddress, ApplicationCode, null);
        }
        
        /// <remarks/>
        public void VCM_AutoURL_Validate_User_InfoAsync(string URLEncrypted, string IPAddress, int ApplicationCode, object userState) {
            if ((this.VCM_AutoURL_Validate_User_InfoOperationCompleted == null)) {
                this.VCM_AutoURL_Validate_User_InfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVCM_AutoURL_Validate_User_InfoOperationCompleted);
            }
            this.InvokeAsync("VCM_AutoURL_Validate_User_Info", new object[] {
                        URLEncrypted,
                        IPAddress,
                        ApplicationCode}, this.VCM_AutoURL_Validate_User_InfoOperationCompleted, userState);
        }
        
        private void OnVCM_AutoURL_Validate_User_InfoOperationCompleted(object arg) {
            if ((this.VCM_AutoURL_Validate_User_InfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VCM_AutoURL_Validate_User_InfoCompleted(this, new VCM_AutoURL_Validate_User_InfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUtcSqlServerDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUtcSqlServerDate() {
            object[] results = this.Invoke("GetUtcSqlServerDate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUtcSqlServerDateAsync() {
            this.GetUtcSqlServerDateAsync(null);
        }
        
        /// <remarks/>
        public void GetUtcSqlServerDateAsync(object userState) {
            if ((this.GetUtcSqlServerDateOperationCompleted == null)) {
                this.GetUtcSqlServerDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUtcSqlServerDateOperationCompleted);
            }
            this.InvokeAsync("GetUtcSqlServerDate", new object[0], this.GetUtcSqlServerDateOperationCompleted, userState);
        }
        
        private void OnGetUtcSqlServerDateOperationCompleted(object arg) {
            if ((this.GetUtcSqlServerDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUtcSqlServerDateCompleted(this, new GetUtcSqlServerDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckUserStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long CheckUserStatus(string strEmailId, string strIpAddress) {
            object[] results = this.Invoke("CheckUserStatus", new object[] {
                        strEmailId,
                        strIpAddress});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void CheckUserStatusAsync(string strEmailId, string strIpAddress) {
            this.CheckUserStatusAsync(strEmailId, strIpAddress, null);
        }
        
        /// <remarks/>
        public void CheckUserStatusAsync(string strEmailId, string strIpAddress, object userState) {
            if ((this.CheckUserStatusOperationCompleted == null)) {
                this.CheckUserStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckUserStatusOperationCompleted);
            }
            this.InvokeAsync("CheckUserStatus", new object[] {
                        strEmailId,
                        strIpAddress}, this.CheckUserStatusOperationCompleted, userState);
        }
        
        private void OnCheckUserStatusOperationCompleted(object arg) {
            if ((this.CheckUserStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckUserStatusCompleted(this, new CheckUserStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserLoginActivatationFLag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SetUserLoginActivatationFLag(long lUserID) {
            object[] results = this.Invoke("SetUserLoginActivatationFLag", new object[] {
                        lUserID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SetUserLoginActivatationFLagAsync(long lUserID) {
            this.SetUserLoginActivatationFLagAsync(lUserID, null);
        }
        
        /// <remarks/>
        public void SetUserLoginActivatationFLagAsync(long lUserID, object userState) {
            if ((this.SetUserLoginActivatationFLagOperationCompleted == null)) {
                this.SetUserLoginActivatationFLagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserLoginActivatationFLagOperationCompleted);
            }
            this.InvokeAsync("SetUserLoginActivatationFLag", new object[] {
                        lUserID}, this.SetUserLoginActivatationFLagOperationCompleted, userState);
        }
        
        private void OnSetUserLoginActivatationFLagOperationCompleted(object arg) {
            if ((this.SetUserLoginActivatationFLagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserLoginActivatationFLagCompleted(this, new SetUserLoginActivatationFLagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserPasswordFlag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetUserPasswordFlag(long lUserID, int iFlag, string strEmail) {
            object[] results = this.Invoke("SetUserPasswordFlag", new object[] {
                        lUserID,
                        iFlag,
                        strEmail});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetUserPasswordFlagAsync(long lUserID, int iFlag, string strEmail) {
            this.SetUserPasswordFlagAsync(lUserID, iFlag, strEmail, null);
        }
        
        /// <remarks/>
        public void SetUserPasswordFlagAsync(long lUserID, int iFlag, string strEmail, object userState) {
            if ((this.SetUserPasswordFlagOperationCompleted == null)) {
                this.SetUserPasswordFlagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserPasswordFlagOperationCompleted);
            }
            this.InvokeAsync("SetUserPasswordFlag", new object[] {
                        lUserID,
                        iFlag,
                        strEmail}, this.SetUserPasswordFlagOperationCompleted, userState);
        }
        
        private void OnSetUserPasswordFlagOperationCompleted(object arg) {
            if ((this.SetUserPasswordFlagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserPasswordFlagCompleted(this, new SetUserPasswordFlagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangePassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangePassword(long lUserId, string oldPassword, string newPassword) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        lUserId,
                        oldPassword,
                        newPassword});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(long lUserId, string oldPassword, string newPassword) {
            this.ChangePasswordAsync(lUserId, oldPassword, newPassword, null);
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(long lUserId, string oldPassword, string newPassword, object userState) {
            if ((this.ChangePasswordOperationCompleted == null)) {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                        lUserId,
                        oldPassword,
                        newPassword}, this.ChangePasswordOperationCompleted, userState);
        }
        
        private void OnChangePasswordOperationCompleted(object arg) {
            if ((this.ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmailIDFromUserID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmailIDFromUserID(long lUserId) {
            object[] results = this.Invoke("GetEmailIDFromUserID", new object[] {
                        lUserId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmailIDFromUserIDAsync(long lUserId) {
            this.GetEmailIDFromUserIDAsync(lUserId, null);
        }
        
        /// <remarks/>
        public void GetEmailIDFromUserIDAsync(long lUserId, object userState) {
            if ((this.GetEmailIDFromUserIDOperationCompleted == null)) {
                this.GetEmailIDFromUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmailIDFromUserIDOperationCompleted);
            }
            this.InvokeAsync("GetEmailIDFromUserID", new object[] {
                        lUserId}, this.GetEmailIDFromUserIDOperationCompleted, userState);
        }
        
        private void OnGetEmailIDFromUserIDOperationCompleted(object arg) {
            if ((this.GetEmailIDFromUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmailIDFromUserIDCompleted(this, new GetEmailIDFromUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserCustomerDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserCustomerDetails(long lUserId) {
            object[] results = this.Invoke("GetUserCustomerDetails", new object[] {
                        lUserId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserCustomerDetailsAsync(long lUserId) {
            this.GetUserCustomerDetailsAsync(lUserId, null);
        }
        
        /// <remarks/>
        public void GetUserCustomerDetailsAsync(long lUserId, object userState) {
            if ((this.GetUserCustomerDetailsOperationCompleted == null)) {
                this.GetUserCustomerDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserCustomerDetailsOperationCompleted);
            }
            this.InvokeAsync("GetUserCustomerDetails", new object[] {
                        lUserId}, this.GetUserCustomerDetailsOperationCompleted, userState);
        }
        
        private void OnGetUserCustomerDetailsOperationCompleted(object arg) {
            if ((this.GetUserCustomerDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserCustomerDetailsCompleted(this, new GetUserCustomerDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserSecurityQuestion_And_Answer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserSecurityQuestion_And_Answer(string strEmail) {
            object[] results = this.Invoke("GetUserSecurityQuestion_And_Answer", new object[] {
                        strEmail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserSecurityQuestion_And_AnswerAsync(string strEmail) {
            this.GetUserSecurityQuestion_And_AnswerAsync(strEmail, null);
        }
        
        /// <remarks/>
        public void GetUserSecurityQuestion_And_AnswerAsync(string strEmail, object userState) {
            if ((this.GetUserSecurityQuestion_And_AnswerOperationCompleted == null)) {
                this.GetUserSecurityQuestion_And_AnswerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserSecurityQuestion_And_AnswerOperationCompleted);
            }
            this.InvokeAsync("GetUserSecurityQuestion_And_Answer", new object[] {
                        strEmail}, this.GetUserSecurityQuestion_And_AnswerOperationCompleted, userState);
        }
        
        private void OnGetUserSecurityQuestion_And_AnswerOperationCompleted(object arg) {
            if ((this.GetUserSecurityQuestion_And_AnswerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserSecurityQuestion_And_AnswerCompleted(this, new GetUserSecurityQuestion_And_AnswerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetUserID(string strEmailId) {
            object[] results = this.Invoke("GetUserID", new object[] {
                        strEmailId});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserIDAsync(string strEmailId) {
            this.GetUserIDAsync(strEmailId, null);
        }
        
        /// <remarks/>
        public void GetUserIDAsync(string strEmailId, object userState) {
            if ((this.GetUserIDOperationCompleted == null)) {
                this.GetUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserIDOperationCompleted);
            }
            this.InvokeAsync("GetUserID", new object[] {
                        strEmailId}, this.GetUserIDOperationCompleted, userState);
        }
        
        private void OnGetUserIDOperationCompleted(object arg) {
            if ((this.GetUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserIDCompleted(this, new GetUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCMEUserIdFromGuid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCMEUserIdFromGuid(string pGuid) {
            object[] results = this.Invoke("GetCMEUserIdFromGuid", new object[] {
                        pGuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCMEUserIdFromGuidAsync(string pGuid) {
            this.GetCMEUserIdFromGuidAsync(pGuid, null);
        }
        
        /// <remarks/>
        public void GetCMEUserIdFromGuidAsync(string pGuid, object userState) {
            if ((this.GetCMEUserIdFromGuidOperationCompleted == null)) {
                this.GetCMEUserIdFromGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCMEUserIdFromGuidOperationCompleted);
            }
            this.InvokeAsync("GetCMEUserIdFromGuid", new object[] {
                        pGuid}, this.GetCMEUserIdFromGuidOperationCompleted, userState);
        }
        
        private void OnGetCMEUserIdFromGuidOperationCompleted(object arg) {
            if ((this.GetCMEUserIdFromGuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCMEUserIdFromGuidCompleted(this, new GetCMEUserIdFromGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveCMEUserGuid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveCMEUserGuid(long pUserId, string pGUID) {
            object[] results = this.Invoke("SaveCMEUserGuid", new object[] {
                        pUserId,
                        pGUID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveCMEUserGuidAsync(long pUserId, string pGUID) {
            this.SaveCMEUserGuidAsync(pUserId, pGUID, null);
        }
        
        /// <remarks/>
        public void SaveCMEUserGuidAsync(long pUserId, string pGUID, object userState) {
            if ((this.SaveCMEUserGuidOperationCompleted == null)) {
                this.SaveCMEUserGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCMEUserGuidOperationCompleted);
            }
            this.InvokeAsync("SaveCMEUserGuid", new object[] {
                        pUserId,
                        pGUID}, this.SaveCMEUserGuidOperationCompleted, userState);
        }
        
        private void OnSaveCMEUserGuidOperationCompleted(object arg) {
            if ((this.SaveCMEUserGuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCMEUserGuidCompleted(this, new SaveCMEUserGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidateUser(string username, string password) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string username, string password) {
            this.ValidateUserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string username, string password, object userState) {
            if ((this.ValidateUserOperationCompleted == null)) {
                this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
            }
            this.InvokeAsync("ValidateUser", new object[] {
                        username,
                        password}, this.ValidateUserOperationCompleted, userState);
        }
        
        private void OnValidateUserOperationCompleted(object arg) {
            if ((this.ValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserstate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserstate() {
            object[] results = this.Invoke("GetUserstate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserstateAsync() {
            this.GetUserstateAsync(null);
        }
        
        /// <remarks/>
        public void GetUserstateAsync(object userState) {
            if ((this.GetUserstateOperationCompleted == null)) {
                this.GetUserstateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserstateOperationCompleted);
            }
            this.InvokeAsync("GetUserstate", new object[0], this.GetUserstateOperationCompleted, userState);
        }
        
        private void OnGetUserstateOperationCompleted(object arg) {
            if ((this.GetUserstateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserstateCompleted(this, new GetUserstateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAutoURLGeoIPInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAutoURLGeoIPInfo(string IPAddress) {
            object[] results = this.Invoke("GetAutoURLGeoIPInfo", new object[] {
                        IPAddress});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAutoURLGeoIPInfoAsync(string IPAddress) {
            this.GetAutoURLGeoIPInfoAsync(IPAddress, null);
        }
        
        /// <remarks/>
        public void GetAutoURLGeoIPInfoAsync(string IPAddress, object userState) {
            if ((this.GetAutoURLGeoIPInfoOperationCompleted == null)) {
                this.GetAutoURLGeoIPInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAutoURLGeoIPInfoOperationCompleted);
            }
            this.InvokeAsync("GetAutoURLGeoIPInfo", new object[] {
                        IPAddress}, this.GetAutoURLGeoIPInfoOperationCompleted, userState);
        }
        
        private void OnGetAutoURLGeoIPInfoOperationCompleted(object arg) {
            if ((this.GetAutoURLGeoIPInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAutoURLGeoIPInfoCompleted(this, new GetAutoURLGeoIPInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BeastApps_SharedAutoURL_Validate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BeastApps_SharedAutoURL_Validate(string pRefId) {
            object[] results = this.Invoke("BeastApps_SharedAutoURL_Validate", new object[] {
                        pRefId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BeastApps_SharedAutoURL_ValidateAsync(string pRefId) {
            this.BeastApps_SharedAutoURL_ValidateAsync(pRefId, null);
        }
        
        /// <remarks/>
        public void BeastApps_SharedAutoURL_ValidateAsync(string pRefId, object userState) {
            if ((this.BeastApps_SharedAutoURL_ValidateOperationCompleted == null)) {
                this.BeastApps_SharedAutoURL_ValidateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeastApps_SharedAutoURL_ValidateOperationCompleted);
            }
            this.InvokeAsync("BeastApps_SharedAutoURL_Validate", new object[] {
                        pRefId}, this.BeastApps_SharedAutoURL_ValidateOperationCompleted, userState);
        }
        
        private void OnBeastApps_SharedAutoURL_ValidateOperationCompleted(object arg) {
            if ((this.BeastApps_SharedAutoURL_ValidateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeastApps_SharedAutoURL_ValidateCompleted(this, new BeastApps_SharedAutoURL_ValidateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserName() {
            object[] results = this.Invoke("GetUserName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserNameAsync() {
            this.GetUserNameAsync(null);
        }
        
        /// <remarks/>
        public void GetUserNameAsync(object userState) {
            if ((this.GetUserNameOperationCompleted == null)) {
                this.GetUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserNameOperationCompleted);
            }
            this.InvokeAsync("GetUserName", new object[0], this.GetUserNameOperationCompleted, userState);
        }
        
        private void OnGetUserNameOperationCompleted(object arg) {
            if ((this.GetUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserNameCompleted(this, new GetUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] AuthenticateUser(string username, string password) {
            object[] results = this.Invoke("AuthenticateUser", new object[] {
                        username,
                        password});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string username, string password) {
            this.AuthenticateUserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string username, string password, object userState) {
            if ((this.AuthenticateUserOperationCompleted == null)) {
                this.AuthenticateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUser", new object[] {
                        username,
                        password}, this.AuthenticateUserOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserOperationCompleted(object arg) {
            if ((this.AuthenticateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BeastApps_SharedAutoURL_UpdateClickCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BeastApps_SharedAutoURL_UpdateClickCount(string pRefId) {
            this.Invoke("BeastApps_SharedAutoURL_UpdateClickCount", new object[] {
                        pRefId});
        }
        
        /// <remarks/>
        public void BeastApps_SharedAutoURL_UpdateClickCountAsync(string pRefId) {
            this.BeastApps_SharedAutoURL_UpdateClickCountAsync(pRefId, null);
        }
        
        /// <remarks/>
        public void BeastApps_SharedAutoURL_UpdateClickCountAsync(string pRefId, object userState) {
            if ((this.BeastApps_SharedAutoURL_UpdateClickCountOperationCompleted == null)) {
                this.BeastApps_SharedAutoURL_UpdateClickCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeastApps_SharedAutoURL_UpdateClickCountOperationCompleted);
            }
            this.InvokeAsync("BeastApps_SharedAutoURL_UpdateClickCount", new object[] {
                        pRefId}, this.BeastApps_SharedAutoURL_UpdateClickCountOperationCompleted, userState);
        }
        
        private void OnBeastApps_SharedAutoURL_UpdateClickCountOperationCompleted(object arg) {
            if ((this.BeastApps_SharedAutoURL_UpdateClickCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeastApps_SharedAutoURL_UpdateClickCountCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BeastApps_SharedAutoURL_StoppedByInitiator", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BeastApps_SharedAutoURL_StoppedByInitiator(int pUserID, string pInstanceID) {
            this.Invoke("BeastApps_SharedAutoURL_StoppedByInitiator", new object[] {
                        pUserID,
                        pInstanceID});
        }
        
        /// <remarks/>
        public void BeastApps_SharedAutoURL_StoppedByInitiatorAsync(int pUserID, string pInstanceID) {
            this.BeastApps_SharedAutoURL_StoppedByInitiatorAsync(pUserID, pInstanceID, null);
        }
        
        /// <remarks/>
        public void BeastApps_SharedAutoURL_StoppedByInitiatorAsync(int pUserID, string pInstanceID, object userState) {
            if ((this.BeastApps_SharedAutoURL_StoppedByInitiatorOperationCompleted == null)) {
                this.BeastApps_SharedAutoURL_StoppedByInitiatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeastApps_SharedAutoURL_StoppedByInitiatorOperationCompleted);
            }
            this.InvokeAsync("BeastApps_SharedAutoURL_StoppedByInitiator", new object[] {
                        pUserID,
                        pInstanceID}, this.BeastApps_SharedAutoURL_StoppedByInitiatorOperationCompleted, userState);
        }
        
        private void OnBeastApps_SharedAutoURL_StoppedByInitiatorOperationCompleted(object arg) {
            if ((this.BeastApps_SharedAutoURL_StoppedByInitiatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeastApps_SharedAutoURL_StoppedByInitiatorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendUserLoginMail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendUserLoginMail(string pMailType, string pLoginUserEmail, string pClient, string pIpAddress) {
            this.Invoke("SendUserLoginMail", new object[] {
                        pMailType,
                        pLoginUserEmail,
                        pClient,
                        pIpAddress});
        }
        
        /// <remarks/>
        public void SendUserLoginMailAsync(string pMailType, string pLoginUserEmail, string pClient, string pIpAddress) {
            this.SendUserLoginMailAsync(pMailType, pLoginUserEmail, pClient, pIpAddress, null);
        }
        
        /// <remarks/>
        public void SendUserLoginMailAsync(string pMailType, string pLoginUserEmail, string pClient, string pIpAddress, object userState) {
            if ((this.SendUserLoginMailOperationCompleted == null)) {
                this.SendUserLoginMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUserLoginMailOperationCompleted);
            }
            this.InvokeAsync("SendUserLoginMail", new object[] {
                        pMailType,
                        pLoginUserEmail,
                        pClient,
                        pIpAddress}, this.SendUserLoginMailOperationCompleted, userState);
        }
        
        private void OnSendUserLoginMailOperationCompleted(object arg) {
            if ((this.SendUserLoginMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUserLoginMailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetUserPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ResetUserPassword(string strUserLoginId, string strIpAddress, string strClient) {
            object[] results = this.Invoke("ResetUserPassword", new object[] {
                        strUserLoginId,
                        strIpAddress,
                        strClient});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ResetUserPasswordAsync(string strUserLoginId, string strIpAddress, string strClient) {
            this.ResetUserPasswordAsync(strUserLoginId, strIpAddress, strClient, null);
        }
        
        /// <remarks/>
        public void ResetUserPasswordAsync(string strUserLoginId, string strIpAddress, string strClient, object userState) {
            if ((this.ResetUserPasswordOperationCompleted == null)) {
                this.ResetUserPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetUserPasswordOperationCompleted);
            }
            this.InvokeAsync("ResetUserPassword", new object[] {
                        strUserLoginId,
                        strIpAddress,
                        strClient}, this.ResetUserPasswordOperationCompleted, userState);
        }
        
        private void OnResetUserPasswordOperationCompleted(object arg) {
            if ((this.ResetUserPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetUserPasswordCompleted(this, new ResetUserPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void VCM_AutoURL_Validate_User_InfoCompletedEventHandler(object sender, VCM_AutoURL_Validate_User_InfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VCM_AutoURL_Validate_User_InfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VCM_AutoURL_Validate_User_InfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUtcSqlServerDateCompletedEventHandler(object sender, GetUtcSqlServerDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUtcSqlServerDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUtcSqlServerDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CheckUserStatusCompletedEventHandler(object sender, CheckUserStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckUserStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckUserStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetUserLoginActivatationFLagCompletedEventHandler(object sender, SetUserLoginActivatationFLagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserLoginActivatationFLagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetUserLoginActivatationFLagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetUserPasswordFlagCompletedEventHandler(object sender, SetUserPasswordFlagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserPasswordFlagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetUserPasswordFlagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetEmailIDFromUserIDCompletedEventHandler(object sender, GetEmailIDFromUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmailIDFromUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmailIDFromUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUserCustomerDetailsCompletedEventHandler(object sender, GetUserCustomerDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserCustomerDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserCustomerDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUserSecurityQuestion_And_AnswerCompletedEventHandler(object sender, GetUserSecurityQuestion_And_AnswerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserSecurityQuestion_And_AnswerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserSecurityQuestion_And_AnswerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUserIDCompletedEventHandler(object sender, GetUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCMEUserIdFromGuidCompletedEventHandler(object sender, GetCMEUserIdFromGuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCMEUserIdFromGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCMEUserIdFromGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SaveCMEUserGuidCompletedEventHandler(object sender, SaveCMEUserGuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCMEUserGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCMEUserGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUserstateCompletedEventHandler(object sender, GetUserstateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserstateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserstateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAutoURLGeoIPInfoCompletedEventHandler(object sender, GetAutoURLGeoIPInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAutoURLGeoIPInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAutoURLGeoIPInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BeastApps_SharedAutoURL_ValidateCompletedEventHandler(object sender, BeastApps_SharedAutoURL_ValidateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeastApps_SharedAutoURL_ValidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BeastApps_SharedAutoURL_ValidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUserNameCompletedEventHandler(object sender, GetUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AuthenticateUserCompletedEventHandler(object sender, AuthenticateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BeastApps_SharedAutoURL_UpdateClickCountCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BeastApps_SharedAutoURL_StoppedByInitiatorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendUserLoginMailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ResetUserPasswordCompletedEventHandler(object sender, ResetUserPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetUserPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetUserPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591