<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Cart.aspx.cs" Inherits="Savory.Cart" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="bs-docs-section">
        <div class="row">
            <asp:GridView ID="cartlist" runat="server" CssClass="tblClass hdrBorder table table-condensed"
                OnRowEditing="cartlist_RowEditing"
                OnRowCancelingEdit="cartlist_RowCancelingEdit"
                OnRowUpdating="cartlist_RowUpdating"
                OnPageIndexChanging="cartlist_PageIndexChanging" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" >
            </asp:GridView>
        </div>
    </div>
</asp:Content>
