//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEAST_WEB_PUBLISHER.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEAST_WEB_PUBLISHER.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Beastlogo {
            get {
                object obj = ResourceManager.GetObject("Beastlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataEntry {
            get {
                object obj = ResourceManager.GetObject("DataEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dbdimg {
            get {
                object obj = ResourceManager.GetObject("dbdimg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dbEntry {
            get {
                object obj = ResourceManager.GetObject("dbEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HtmlElement {
            get {
                object obj = ResourceManager.GetObject("HtmlElement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PathSelcet {
            get {
                object obj = ResourceManager.GetObject("PathSelcet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PathSelcet1 {
            get {
                object obj = ResourceManager.GetObject("PathSelcet1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sisTxml {
            get {
                object obj = ResourceManager.GetObject("sisTxml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sisTxml1 {
            get {
                object obj = ResourceManager.GetObject("sisTxml1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 153.
        /// </summary>
        internal static string vcm_calc_CapFloorVols {
            get {
                return ResourceManager.GetString("vcm_calc_CapFloorVols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string vcm_calc_CMCapFloor {
            get {
                return ResourceManager.GetString("vcm_calc_CMCapFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string vcm_calc_CMEDSF_vs_Bond_Future {
            get {
                return ResourceManager.GetString("vcm_calc_CMEDSF_vs_Bond_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string vcm_calc_CMEDSF_vs_EuroDollar_Future_Hedge {
            get {
                return ResourceManager.GetString("vcm_calc_CMEDSF_vs_EuroDollar_Future_Hedge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string vcm_calc_cmefuture {
            get {
                return ResourceManager.GetString("vcm_calc_cmefuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string vcm_calc_cmeotcpage {
            get {
                return ResourceManager.GetString("vcm_calc_cmeotcpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9091.
        /// </summary>
        internal static string vcm_calc_CPINSA {
            get {
                return ResourceManager.GetString("vcm_calc_CPINSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 229.
        /// </summary>
        internal static string vcm_calc_European_Swaption {
            get {
                return ResourceManager.GetString("vcm_calc_European_Swaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 215.
        /// </summary>
        internal static string vcm_calc_iimswappagemid {
            get {
                return ResourceManager.GetString("vcm_calc_iimswappagemid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string vcm_calc_irsfuture {
            get {
                return ResourceManager.GetString("vcm_calc_irsfuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9095.
        /// </summary>
        internal static string vcm_calc_ISDAFix {
            get {
                return ResourceManager.GetString("vcm_calc_ISDAFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 153.
        /// </summary>
        internal static string vcm_calc_MedTermSwapPage {
            get {
                return ResourceManager.GetString("vcm_calc_MedTermSwapPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 253.
        /// </summary>
        internal static string vcm_calc_MidTermSwapPageMid {
            get {
                return ResourceManager.GetString("vcm_calc_MidTermSwapPageMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string vcm_calc_Pers_Med_Term_Swap_Mid {
            get {
                return ResourceManager.GetString("vcm_calc_Pers_Med_Term_Swap_Mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 224.
        /// </summary>
        internal static string vcm_calc_ShortTermSwapPage {
            get {
                return ResourceManager.GetString("vcm_calc_ShortTermSwapPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 194.
        /// </summary>
        internal static string vcm_calc_SimpleSwapCalculator {
            get {
                return ResourceManager.GetString("vcm_calc_SimpleSwapCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 145.
        /// </summary>
        internal static string vcm_calc_SwapBondCalculator {
            get {
                return ResourceManager.GetString("vcm_calc_SwapBondCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 210.
        /// </summary>
        internal static string vcm_calc_SwapDiffCalculator {
            get {
                return ResourceManager.GetString("vcm_calc_SwapDiffCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 171.
        /// </summary>
        internal static string vcm_calc_SwapSwitch {
            get {
                return ResourceManager.GetString("vcm_calc_SwapSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string vcm_calc_swaptionVolPremStrike {
            get {
                return ResourceManager.GetString("vcm_calc_swaptionVolPremStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xt {
            get {
                object obj = ResourceManager.GetObject("xt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
